---
- name: Create Filesystems
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev:    "{{ item.device }}"
  become: true
  with_items: 
    - "{{ filesystems }}"
  when:
    - filesystems is defined
